-- PragmAda Reusable Component (PragmARC)
-- Copyright (C) by PragmAda Software Engineering
-- SPDX-License-Identifier: BSD-3-Clause
-- See https://spdx.org/licenses/
-- If you find this software useful, please let me know, either through
-- github.com/jrcarter or directly to pragmada@pragmada.x10hosting.com
-- **************************************************************************
--
-- Root of the Randomness hierarchy
--
-- Ada 95 and later define 2 standard random-number packages, Ada.Numerics.Float_Random & Ada.Numerics.Discrete_Random.
-- However, the random-number algorithm used by these packages is implementation defined. This package hierarchy provides portable
-- generators of known, good quality, should portability or the algorithm be a concern.
--
-- History:
-- 2025 Jul 01     J. Carter          V1.2--Use SPDX license format
-- 2020 Dec 01     J. Carter          V1.1--Changed elaboration pragmas to aspects
-- 2020 Nov 01     J. Carter          V1.0--Initial Ada-12 version
--
package PragmARC.Randomness with Pure is
   -- Empty
end PragmARC.Randomness;
